const DUMMY_PRODUCT_DATA = [
  {
    id: 'a1',
    manufacturer: 'Wrangler',
    productName: 'slhrelax manzo fleece',
    type: 'cardigans',
    sexOrGroup: 'm',
    sizes: [
      { size: 'S', amount: 5 },
      { size: 'M', amount: 7 },
      { size: 'L', amount: 0 },
      { size: 'XL', amount: 3 },
      { size: 'XXL', amount: 0 },
    ],
    previewPics: [
      'https://cdn.shopify.com/s/files/1/0012/8935/5319/products/LC09171003RL_Pic-1_800x.jpg?v=1634547582',
      'https://amiamalia.com/wp-content/uploads/2019/12/Cable-Knit-Cardigan-for-men-Anthracite-2-003.jpg',
    ],
    price: 79,
    discount: 30,
    productTag: 'featured',
  },
  {
    id: 'a2',
    manufacturer: 'Wrangler',
    productName: 'slhrelax manzo fleece',
    type: 'cardigans',
    sexOrGroup: 'm',
    sizes: [
      { size: 'S', amount: 5 },
      { size: 'M', amount: 0 },
      { size: 'L', amount: 4 },
      { size: 'XL', amount: 3 },
      { size: 'XXL', amount: 0 },
    ],
    previewPics: [
      'https://xcdn.next.co.uk/Common/Items/Default/Default/ItemImages/Search/224x336/A94031.jpg',
      'https://assets.maisoncashmere.com/media/catalog/product/m/c/mcm004-men-cashmere-cardigan-sweater-03.jpg',
    ],
    price: 76,
    discount: 5,
    productTag: 'featured',
  },
  {
    id: 'a3',
    manufacturer: 'Wrangler',
    productName: 'slhrelax manzo fleece',
    type: 'cardigans',
    sexOrGroup: 'm',
    sizes: [
      { size: 'S', amount: 5 },
      { size: 'M', amount: 7 },
      { size: 'L', amount: 0 },
      { size: 'XL', amount: 3 },
      { size: 'XXL', amount: 0 },
    ],
    previewPics: [
      'https://cdn.shopify.com/s/files/1/0012/8935/5319/products/LC09171003RL_Pic-1_800x.jpg?v=1634547582',
    ],
    price: 79,
    discount: 0,
  },
  {
    id: 'a4',
    manufacturer: 'Wrangler',
    productName: 'slhrelax manzo fleece',
    type: 'cardigans',
    sexOrGroup: 'm',
    sizes: [
      { size: 'S', amount: 5 },
      { size: 'M', amount: 7 },
      { size: 'L', amount: 0 },
      { size: 'XL', amount: 3 },
      { size: 'XXL', amount: 0 },
    ],
    previewPics: [
      'https://xcdn.next.co.uk/Common/Items/Default/Default/ItemImages/Search/224x336/A94031.jpg',
    ],
    price: 76,
    discount: 5,
  },
  {
    id: 'a5',
    manufacturer: 'Wrangler',
    productName: 'slhrelax manzo fleece',
    type: 'cardigans',
    sexOrGroup: 'm',
    sizes: [
      { size: 'S', amount: 5 },
      { size: 'M', amount: 7 },
      { size: 'L', amount: 0 },
      { size: 'XL', amount: 3 },
      { size: 'XXL', amount: 0 },
    ],
    previewPics: [
      'https://cdn.shopify.com/s/files/1/0012/8935/5319/products/LC09171003RL_Pic-1_800x.jpg?v=1634547582',
    ],
    price: 79,
    discount: 0,
  },
  {
    id: 'a6',
    manufacturer: 'Wrangler',
    productName: 'slhrelax manzo fleece',
    type: 'cardigans',
    sexOrGroup: 'm',
    sizes: [
      { size: 'S', amount: 5 },
      { size: 'M', amount: 7 },
      { size: 'L', amount: 0 },
      { size: 'XL', amount: 3 },
      { size: 'XXL', amount: 0 },
    ],
    previewPics: [
      'https://xcdn.next.co.uk/Common/Items/Default/Default/ItemImages/Search/224x336/A94031.jpg',
    ],
    price: 76,
    discount: 5,
  },
  {
    id: 'a7',
    manufacturer: 'Wrangler',
    productName: 'slhrelax manzo fleece',
    type: 'cardigans',
    sexOrGroup: 'm',
    sizes: [
      { size: 'S', amount: 5 },
      { size: 'M', amount: 7 },
      { size: 'L', amount: 0 },
      { size: 'XL', amount: 3 },
      { size: 'XXL', amount: 0 },
    ],
    previewPics: [
      'https://cdn.shopify.com/s/files/1/0012/8935/5319/products/LC09171003RL_Pic-1_800x.jpg?v=1634547582',
    ],
    price: 79,
    discount: 20,
  },
  {
    manufacturer: 'Mavi',
    productName: 'Mavi - BAG',
    type: 'bags',
    sexOrGroup: 'f',
    sizes: [{ size: 'One Size', amount: 5 }],
    previewPics: [
      'https://cdn.shopify.com/s/files/1/2225/5907/products/ecomm-Tote-2448.jpg?v=1622961112',
      'https://cdn.shopify.com/s/files/1/2225/5907/products/ecomm-Tote-2470.jpg?v=1622961114&width=493w',
    ],
    price: 149.99,
    discount: 0,
  },
];

export default DUMMY_PRODUCT_DATA;
